--- # install java download and install tomact
- hosts: all
  become: true
  user: ansible

  tasks: 
   - name: install java
     yum: 
       name: java
       state: present

   - name: download tomcat
     get_url: 
       url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.67/bin/apache-tomcat-9.0.67.tar.gz
       dest: /opt

   - name: extract file
     unarchive:
       src: /opt/apache-tomcat-9.0.67.tar.gz
       dest: /opt
       remote_src: yes

   - name: providing executable permissions
     file:
       path: /opt/apache-tomcat-9.0.67/bin/startup.sh
       mode: 0777

   - name: start tomcat service
     shell: nohup ./startup.sh
     args:
       chdir: /opt/apache-tomcat-9.0.67/bin


