--- 
- hosts: all
  become: true

  tasks:
    - name: installing s/w
      yum:
        name: httpd
        state: installed

    - name: start service
      service:
        name: httpd
        state: started
